[workspace]
members = [
    "cargo-axum", "day1", "day11", "day4", "day5", "day6", "day7", "day8",
    "minus1", "server", 
]

default-members = ["server"]

exclude = [
    "cargo-axum", 
]

resolver = "2"
