[package]
name = "minus1"
version = "0.1.0"
edition = "2021"

[lib]
name = "minus1"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
serde = { version = "1.0.195", features = ["derive"] }
